#!/usr/bin/env python3
"""Generate one page stub per site record: data/sites/<id>.yml -> sites/<id>.md.

Stubs are tiny committed front-matter files; the site-record layout renders
everything from site.data.sites[<id>] at build time. Removes stubs whose
record is gone. Idempotent.
"""
from __future__ import annotations

import json
import pathlib

import yaml

ROOT = pathlib.Path(__file__).resolve().parent.parent
SITES = ROOT / "data" / "sites"
STUBS = ROOT / "sites"

STUBS.mkdir(exist_ok=True)
records = {}
for path in sorted(SITES.glob("*.yml")) if SITES.is_dir() else []:
    doc = yaml.safe_load(path.read_text(encoding="utf-8"))
    records[path.stem] = doc

changed = 0
for rid, rec in records.items():
    stub = STUBS / f"{rid}.md"
    loc = rec.get("location") or {}
    # A geocoded record shows a locator map — flag the stub so the theme loads
    # the (vendored) map assets only on those pages.
    has_geo = loc.get("lat") is not None and loc.get("lon") is not None
    body = (
        "---\n"
        "# GENERATED by scripts/gen-pages.sh from data/sites/ — do not hand-edit.\n"
        "layout: site-record\n"
        f"site_id: {rid}\n"
        f"title: {json.dumps(rec.get('name', rid))}\n"
        f"permalink: /sites/{rid}/\n"
        + ("map: true\n" if has_geo else "")
        + "---\n"
    )
    if not stub.exists() or stub.read_text(encoding="utf-8") != body:
        stub.write_text(body, encoding="utf-8")
        changed += 1

removed = 0
for stub in sorted(STUBS.glob("*.md")):
    if stub.name != "index.md" and stub.stem not in records:
        stub.unlink()
        removed += 1

print(f"gen-pages: {len(records)} records, {changed} stub(s) written, {removed} removed")
